# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# this yaml is the simplest mode to deploy doris with fe and be.
# the log and be storage use `EmptyDir` mode as disk. when the pod restart the log and storage will lost.
# This yaml only for experience deploy and usability on k8s about doris.
apiVersion: doris.selectdb.com/v1
kind: DorisCluster
metadata:
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: doriscluster-sample
    app.kubernetes.io/part-of: doris-operator
  name: doriscluster-sample
spec:
  feSpec:
    configMapInfo:
      configMapName: fe-conf
      resolveKey: fe.conf
    # service:
    #   type: NodePort
    # persistentVolumes:
    # - name: fe-meta
    #   mountPath: /opt/apache-doris/fe/doris-meta
    #   persistentVolumeClaimSpec:
    #     storageClassName: openebs-hostpath
    #     accessModes:
    #     - ReadWriteOnce
    #     resources:
    #       requests:
    #         storage: 10Gi
    # - name: fe-log            
    #   mountPath: /opt/apache-doris/fe/log
    #   persistentVolumeClaimSpec:
    #     storageClassName: openebs-hostpath
    #     accessModes:
    #     - ReadWriteOnce
    #     resources:
    #       requests:
    #         storage: 10Gi
    replicas: 1
    electionNumber: 1
    limits:
      cpu: 4
      memory: 12Gi
    requests:
      cpu: 4
      memory: 12Gi
    image: selectdb/doris.fe-ubuntu:2.0.15
  beSpec:
    configMapInfo:
      configMapName: be-conf
      resolveKey: be.conf
    # service:
    #   type: NodePort
    # persistentVolumes:
    # - mountPath: /opt/apache-doris/be/storage
    #   name: be-storage
    #   persistentVolumeClaimSpec:
    #     storageClassName: openebs-hostpath
    #     accessModes:
    #       - ReadWriteOnce
    #     resources:
    #       requests:
    #         storage: 10Gi
    # - mountPath: /opt/apache-doris/be/log
    #   name: belog
    #   persistentVolumeClaimSpec:
    #     storageClassName: openebs-hostpath
    #     accessModes:
    #     - ReadWriteOnce
    #     resources:
    #       requests:
    #         storage: 10Gi
    replicas: 1
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 8
      memory: 16Gi
    image: selectdb/doris.be-ubuntu:2.0.15