server:
  global:
    ## How frequently to scrape targets by default
    ##
    scrape_interval: 10s
    ## How long until a scrape request times out
    ##
    scrape_timeout: 5s
    ## How frequently to evaluate rules
    ##
    evaluation_interval: 10s
extraScrapeConfigs: |
  - job_name: 'DORIS_CLUSTER' 
    metrics_path: '/metrics' 
    static_configs:
      - targets: ['doriscluster-sample-fe-0.doriscluster-sample-fe-internal.default:8030']
        labels:
          group: fe 
      - targets: ['doriscluster-sample-be-0.doriscluster-sample-be-internal.default:8040']
        labels:
          group: be 

# helm upgrade --install prometheus prometheus-community/prometheus -n monitoring \                                       
#    --set alertmanager.persistence.enabled=false\
#    --set pushgateway.persistentVolume.enabled=false \
#    --set server.persistentVolume.enabled=false \
# -f doris/prom/values.yaml

# helm upgrade --install grafana grafana/grafana -n monitoring \                                       
#    --set adminPassword=admin

# dashboard链接： https://grafana.com/api/dashboards/9734/revisions/5/download 
