server:
  global:
    ## How frequently to scrape targets by default
    ##
    scrape_interval: 10s
    ## How long until a scrape request times out
    ##
    scrape_timeout: 5s
    ## How frequently to evaluate rules
    ##
    evaluation_interval: 10s
extraScrapeConfigs: |
  - job_name: 'DORIS_CLUSTER' 
    metrics_path: '/metrics' 
    static_configs:
      - targets: ['doriscluster-sample-fe-0.doriscluster-sample-fe-internal.default:8030']
        labels:
          group: fe 
      - targets: ['doriscluster-sample-be-0.doriscluster-sample-be-internal.default:8040']
        labels:
          group: be 

